apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: denvertestregistry.azurecr.io/repository:#{Build.BuildId}#
        name: node-app
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: node-svc
  labels: 
    run: node-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: node-app